apiVersion: v1
data:
  ApplicationCustomProcessor.yaml:  |
    application:
      NervIO:
       stream-config:
         client.id: NervIOProcessor-39
         group.id: test-consumer-gr390
         application.id: stateless_processor_id357
       statestore:
         storename: appstore
       jmx.metrics.config:
         collection.interval: 10
       transformer-config:
         customtransform:
           classname: "com.hcl.iAct.Driver"
           config: "{\"storage_type\": \"{{ .Values.script-finder.storage_type }}\",\"keyvault_enabled\": \"{{ .Values.script-finder.keyvault_enabled }}\",\"db_url\": \"{{ .Values.db_url }}\", \"db_minidle\": 1,\"db_maxpoolsize\": 2,\"cronschedule\":\"0 * * ? * *\", \"waittimelimit\":\"7200 SECONDS\", \"bootstrapserver\": \"{{ .Values.script-finder.kafkaserver }}\",\"topic\": \"rundecktopic\",\"keyserializer\": \"{{ .Values.script-finder.keyserializer }}\",\"valueserializer\": \"{{ .Values.script-finder.valueserializer }}\",\"miniourl\": \"{{ .Values.script-finder.miniourl }}\", \"alertmanagerurl\":\"{{ .Values.script-finder.alertmanagerurl }}\", \"kafka.ssl.enable\":\"false\"}"
kind:  ConfigMap
metadata:
  name: scriptfinder-config
