apiVersion: v1
data:
  ApplicationCustomProcessor.yaml:  |
    application:
      NervIO:
       stream-config:
         client.id: NervIOProcessor-39
         group.id: test-consumer-gr390
         application.id: stateless_processor_id357
       statestore:
         storename: appstore
       jmx.metrics.config:
         collection.interval: 10
       transformer-config:
         customtransform:
           classname: "com.hcl.iAct.Driver"
           config: "{\"storage_type\": \"adls\",\"db_url\": \"jdbc:postgresql://postgres.datahub-ns.svc.cluster.local:5432/iact\", \"db_minidle\": 1,\"db_maxpoolsize\": 2,\"cronschedule\":\"0 * * ? * *\", \"waittimelimit\":\"7200 SECONDS\", \"bootstrapserver\": \"cp-kafka.core-ns.svc.cluster.local:9092\",\"topic\": \"rundecktopic\",\"keyserializer\": \"org.apache.kafka.common.serialization.StringSerializer\",\"valueserializer\": \"org.apache.kafka.common.serialization.StringSerializer\",\"miniourl\": \"http://minio.minio-ns.svc.cluster.local:9000\", \"alertmanagerurl\":\"http://alertmanager-headless.observe-ns.svc.cluster.local:9093/api/v1/alerts\", \"kafka.ssl.enable\":\"false\"}"
kind:  ConfigMap
metadata:
  name: scriptfinder-config
