apiVersion: v1
kind: Pod
metadata:
  name: {{ include "database-helm.fullname" . }}-ron-pod
  labels:
  {{- include "database-helm.labels" . | nindent 4 }}
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - date; /configmap/runtimeConfig.sh && sleep 999999
    image: {{ .Values.imageRegistry }}{{ .Values.imageName }}:{{ .Values.imageTag | default .Chart.AppVersion }}
    imagePullPolicy: IfNotPresent
    name: cron-pod
    resources: {{- toYaml .Values.postgres.resources
          | nindent 10 }}
    securityContext:
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65534
    volumeMounts:
    - mountPath: /configmap
      name: configmap
    - mountPath: /database
      name: iact-script
  restartPolicy: Always
  imagePullSecrets:
  - name: acrsecret2
  volumes:
  - configMap:
      defaultMode: 511
      name: config
    name: configmap
  - configMap:
      defaultMode: 511
      name: iact-script
    name: iact-script
