apiVersion: v1
kind: Pod
metadata:
  name: {{ include "database-helm.fullname" . }}-ron-pod
  labels:
  {{- include "database-helm.labels" . | nindent 4 }}
  annotations:
     sidecar.istio.io/proxyCPULimit: "1000m"
     sidecar.istio.io/proxyCPU: "200m"
     sidecar.istio.io/proxyMemory: "128Mi"
     sidecar.istio.io/proxyMemoryLimit: "1Gi" 
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - date; /configmap/runtimeConfig.sh && sleep 999999
    image: {{ .Values.postgres.image.repository }}:{{
          .Values.postgres.image.tag | default .Chart.AppVersion
          }}
    imagePullPolicy: IfNotPresent
    name: cron-pod
    resources: {{- toYaml .Values.postgres.resources
          | nindent 10 }}
    securityContext:
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65534
    volumeMounts:
    - mountPath: /configmap
      name: configmap
    - mountPath: /docker-entrypoint-initdb.d
      name: pgsql-initdb
#    - mountPath: /configmap
#      name: tableconfig
#    - mountPath: /configmap
#      name: iact
  restartPolicy: Always
  imagePullSecrets:
  - name: acrsecret2
  volumes:
  - configMap:
      defaultMode: 511
      name: config
    name: configmap
  - configMap:
      defaultMode: 511
      name: pgsql-initdb-config
    name: pgsql-initdb
#  - configMap:
#      defaultMode: 511
#      name: tableconfig
#    name: tableconfig
#  - configMap:
#      defaultMode: 511
#      name: iactcommandconfig
#    name: iact
