apiVersion: v1
data:
  ApplicationCustomProcessor.yaml:  |
    application:
      NervIO:
        stream-config:
          client.id: NervIOProcessor-30
          group.id: test-consumer-gr200
          application.id: stateless_processor_id295
        statestore:
          storename: appstore
        jmx.metrics.config:
          collection.interval: 10
        transformer-config:
          customtransform:
            classname: "com.hcl.iAct.Executor"
            config: "{\"db_url\": \"{{ .Values.db_url }}\", \"rundeck_user\":\"{{ .Values.rundeck_user }}\",  \"db_minidle\": 1, \"db_maxpoolsize\": 2,\"rundeck_url\":\"{{ .Values.rundeckurl }}\", \"alertmanagerurl\":\"{{ .Values.alertmanagerurl }}\"}"
kind:  ConfigMap
metadata:
  name: command-executors-config
