apiVersion: apps/v1
kind: Deployment
metadata:
  name: iact-command-executors
  labels:
    name: iact-command-executors
spec:
  replicas: {{ .Values.command-executor.replicaCount }}
  selector:
    matchLabels:
      name: iact-command-executors
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPULimit: "1000m"
        sidecar.istio.io/proxyCPU: "200m"
        sidecar.istio.io/proxyMemory: "128Mi"
        sidecar.istio.io/proxyMemoryLimit: "1Gi"
      labels:
        name: iact-command-executors
        app: iact-command-executors
        version: 1.0.0
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - env:
        - name: db_user
          value: "iona_svc"
        - name: db_password
          # value: Abcd1234
          valueFrom:
            secretKeyRef:
              key: POSTGRES-PASSWORD
              name: {{ .Values.secretName}}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.imageRegistry }}{{ .Values.command-executor.imageName }}:{{ .Values.command-executor.imageTag | default .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        name: iact-command-executors
        resources: {{- toYaml .Values.command-executor.iactCommandExecutors.iactCommandExecutors.resources
          | nindent 10 }}
        securityContext:
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/secrets-store
          name: secrets-store-inline
          readOnly: true
        - mountPath: /config/ApplicationCustomProcessor.yaml
          name: command-executors-config
          subPath: ApplicationCustomProcessor.yaml
        - mountPath: /config/Global.yaml
          name: global-config
          subPath: Global.yaml
        - mountPath: /tmp
          name: tmp
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      imagePullSecrets:
      - name: acrsecret2
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      volumes:
      - csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Values.secretProviderClass }}
        name: secrets-store-inline
      - emptyDir: {}
        name: tmp
      - configMap:
          defaultMode: 420
          name: global-config
        name: global-config
      - configMap:
          defaultMode: 420
          name: command-executors-config
        name: command-executors-config
