kubernetesClusterDomain: cluster.local
postgres:
  ports:
  - name: pgservice
    port: 5432
    targetPort: 0
  type: ClusterIP
  postgres:
    image:
      repository: "ionatestregistry.azurecr.io/postgres"
      tag: "20.0"
    resources:
      limits:
        cpu: "1"
        memory: "2Gi"
      requests:
        cpu: "9m"
        memory: "150Mi"
secretName: "mysecret01"
keyVaultName: ""
secretProviderClass: "aws-secrets"
appName: "postgres"
