apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-iact-scripts
  labels:
  {{- include "python-helm.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.python.pvc.pvcIactScripts.storageRequest | quote }}
