apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-iact-scripts
  labels:
  {{- include "python-helm.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: efs-test-sc
  resources:
    requests:
      storage: {{ .Values.pvc.pvcIactScripts.storageRequest | quote }}
