---
releases:

  - name: postgres
    namespace: datahub-ns
    chart: ./postgres-helm/
    installed: true
    wait: true
    timeout: 120
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "./others/*.yaml"

  - name: cp-kafka
    namespace: core-ns
    chart: ./kafka-helm/
    installed: true
    wait: true
    timeout: 300
    needs: 
    - datahub-ns/postgres

  - name: topic
    namespace: core-ns
    chart: ./topic-helm/
    installed: true
    wait: true
    timeout: 20
    needs: 
    - core-ns/cp-kafka

  - name: pgclient
    namespace: datahub-ns
    chart: ./database-helm/
    installed: true
    wait: true
    timeout: 20
    needs:
    - core-ns/cp-kafka

  - name: snowmapper
    namespace: act-ns
    chart: ./snowmapper-helm/
    installed: true
    wait: true
    timeout: 20
    needs:
    - core-ns/cp-kafka

  - name: script-finder
    namespace: act-ns
    chart: ./script-finder-helm/
    installed: true
    wait: true
    timeout: 20
    needs:
    - act-ns/snowmapper

  - name: command-executor
    namespace: act-ns
    chart: ./command-executor-helm/
    installed: true
    wait: true
    timeout: 20
    needs:
    - act-ns/snowmapper

  - name: ansible
    namespace: act-ns
    chart: ./ansible-helm/
    installed: true
    wait: true
    timeout: 20
    needs:
    - core-ns/cp-kafka

  - name: python
    namespace: act-ns
    chart: ./python-helm/
    installed: true
    wait: true
    timeout: 20
    needs:
    - core-ns/cp-kafka

  - name: rundeck
    namespace: act-ns
    chart: ./rundeck-helm/
    installed: true
    wait: true
    timeout: 20
    needs:
    - act-ns/python

  - name: authtoken
    namespace: act-ns
    chart: ./auth-scheduler-helm/
    installed: true
    wait: true
    timeout: 20
    needs:
    - act-ns/rundeck

  - name: alertmanager
    namespace: observe-ns
    chart: ./alertmanager-helm/
    installed: true
    wait: true
    timeout: 20
    needs:
    - act-ns/rundeck
