{{ readFile "./environments.yaml" }}

bases:
  - environments.yaml

hooks:
- events: ["prepare"]
  showlogs: true
  command: "chmod"
  args:
    - "+x"
    - "prerequisite.sh"
- events: ["prepare"]
  showlogs: true
  command: "./prerequisite.sh"
---
templates:
  commonvariables: &commonvariables
    installed: true
    values:
    - ./{{ .Environment.Name }}.yaml

releases:

  - name: postgres
    namespace: datahub-ns
    chart: ./postgres-helm/
    <<: *commonvariables

  - name: kafka
    namespace: core-ns
    chart: ./kafka-helm/
    <<: *commonvariables

  - name: topic
    namespace: core-ns
    chart: ./topic-helm/
    <<: *commonvariables
    needs: 
    - core-ns/kafka

  - name: pgclient
    namespace: datahub-ns
    chart: ./database-helm/
    <<: *commonvariables
    needs:
    - datahub-ns/postgres

  - name: snowmapper
    namespace: act-ns
    chart: ./snowmapper-helm/
    <<: *commonvariables
    needs:
    - core-ns/kafka
    - datahub-ns/postgres

  - name: scriptfinder
    namespace: act-ns
    chart: ./script-finder-helm/
    <<: *commonvariables
    needs:
    - core-ns/kafka
    - datahub-ns/postgres

  - name: commandexecutor
    namespace: act-ns
    chart: ./command-executor-helm/
    <<: *commonvariables
    needs:
    - core-ns/kafka
    - datahub-ns/postgres

  - name: ansible
    namespace: act-ns
    chart: ./ansible-helm/
    <<: *commonvariables

  - name: python
    namespace: act-ns
    chart: ./python-helm/
    <<: *commonvariables

  - name: rundeck
    namespace: act-ns
    chart: ./rundeck-helm/
    <<: *commonvariables
    needs:
    - core-ns/kafka
    - act-ns/python
    - act-ns/ansible

  #- name: authtoken
    #namespace: act-ns
    #chart: ./auth-scheduler-helm/
    #<<: *commonvariables
    #needs:
    #- act-ns/rundeck

  - name: alertmanager
    namespace: observe-ns
    chart: ./alertmanager-helm/
    <<: *commonvariables
