iactCommandExecutors:
  iactCommandExecutors:
    image:
      repository: "ionatestregistry.azurecr.io/iact-command-executors"
      tag: "7.0"
    resources:
      limits:
        cpu: "1"
        memory: 900Mi
      requests:
        cpu: 10m
        memory: 50Mi
  replicas: 1
kubernetesClusterDomain: cluster.local
secretName: "mysecret01"
secretProviderClass: "aws-secrets"
rundeckurl: "https://iona-preprod.odazprivatecloud.com/api/21/job/<job_id>/run"
