apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rundeck-plgin
  labels:
  {{- include "rundeck-helm.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.rundeck.pvc.pvcRundeckPlgin.storageRequest | quote }}
