apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rundeck-plgin
  labels:
  {{- include "rundeck-helm.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.pvcRundeckPlgin.storageRequest | quote }}
