apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rundeck-data
  labels:
  {{- include "rundeck-helm.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: efs-test-sc
  resources:
    requests:
      storage: {{ .Values.pvc.pvcRundeckData.storageRequest | quote }}
