apiVersion: v1
kind: Service
metadata:
  name: {{ include "rundeck-helm.fullname" . }}-rundeck-hl
  labels:
  {{- include "rundeck-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.rundeck.rundeckHl.type }}
  selector:
    app.kubernetes.io/instance: my-rundeck
    app.kubernetes.io/name: rundeck
  ports:
	{{- .Values.rundeck.rundeckHl.ports | toYaml | nindent 2 -}}
