apiVersion: v1
kind: Service
metadata:
  name: ansible-hl
  labels:
    app: ansible
spec:
  type: {{ .Values.ansible.ansibleHl.type }}
  clusterIP: None
  selector:
    app: ansible
  ports:
	{{- .Values.ansible.ansibleHl.ports | toYaml | nindent 2 -}}
