apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ansible-ssh
  labels:
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.pvc.pvcAnsibleSsh.storageRequest | quote }}
