apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ansible-data
  labels:
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: efs-test-sc
  resources:
    requests:
      storage: {{ .Values.pvc.pvcAnsibleData.storageRequest | quote }}
