apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ansible-data
  labels:
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.ansible.pvc.pvcAnsibleData.storageRequest | quote }}
