apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}
  #  namespace: {{ .Values.namespace}}
  labels:
    app: postgres
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
        {{- .Values.postgres.ports | toYaml | nindent 2 -}}

