iactScriptfinder:
  iactScriptfinder:
    image:
      repository: "ionatestregistry.azurecr.io/iact-scriptfinder"
      tag: "12.0"
    resources:
      limits:
        cpu: "1"
        memory: 900Mi
      requests:
        cpu: 500m
        memory: 100Mi
  replicas: 1
kubernetesClusterDomain: cluster.local
secretName: "mysecret01"
secretProviderClass: "aws-secrets"
