#iactScriptfinder:
#  iactScriptfinder:
#    resources:
#      limits:
#        cpu: "1"
#        memory: 900Mi
#      requests:
#        cpu: 500m
#        memory: 100Mi
#kubernetesClusterDomain: cluster.local
#
## 'appName' is the desired name of service to be deployed in pod
#appName: iact-scriptfinder
#
## 'imageRegistry' is the url of registry from which images needs to be pulled e.g. ECR, docker.io, etc
#imageRegistry: "ionatestregistry.azurecr.io/"
#
## 'imageName' is the name of image to be pulled from 'imageRegistry'
#imageName: "iact-scriptfinder"
#
## 'imageTag' that needs to be pulled and deployed in the current deployment e.g. latest
#imageTag: "8.0"
#
## 'replicaCount' is the desired number of replicas for the service being deployed
#replicaCount: 1
#
## 'serviceAccountName' is the name of service account used to apply secret manager IAM policy
#serviceAccountName: iona-demo-sa
#
## 'secretName' is the name defined to secrets in secretproviderclass template at spec.secretName
#secretName: "mysecret01"
#
## 'secretProviderClass' is the name of the secret provider class created in the same namespace
#secretProviderClass: "aws-secrets"
#
## 'storage_type' is the type of storage used to fetch the data from AWS e.g. s3, s3 Glacier, EFS, etc
#storage_type: "s3"
#
## 'root_drl_path' is the actual path of the objects to be fetched from the storageType
##root_drl_path: "iactbucket/iona/iAct/Adapter/decision-service.drl"
#
## 'keyvault_enabled' value can be true or false depending upon the requirements
#keyvault_enabled: "true"
#
## 'db_url' is the URL of the postgres database followed by port number and username
#db_url: "jdbc:postgresql://postgres.datahub-ns.svc.cluster.local:5432/iact"
#
## 'miniourl' is the endpoint URL minio service
#miniourl: "http://minio.minio-ns.svc.cluster.local:9000"
#
## 'kafkaserver' is the bootstrap server name where the 'cp-kafka' service is exposed
#kafkaserver: "cp-kafka.core-ns.svc.cluster.local:9092"
#
## 'keyserializer' is the name of kafka string serializer
#keyserializer: "org.apache.kafka.common.serialization.StringSerializer"
#
## 'valueserializer' is the name of kafka value serializer
#valueserializer: "org.apache.kafka.common.serialization.StringSerializer"
#
## 'alertmanagerurl' is the endpoint URL of alert manager service
#alertmanagerurl: "http://alertmanager-hl.observe-ns.svc.cluster.local:9093/api/v1/alerts"
