hl:
  ports:
  - port: 2022
    targetPort: 0
  type: ClusterIP
kubernetesClusterDomain: cluster.local
pvc:
  pvcIactScripts:
    storageRequest: 10Gi
python:
  python:
    image:
      repository: "ionatestregistry.azurecr.io/python"
      tag: "7.0"
  replicas: 1
