apiVersion: v1
data:
  ApplicationCustomProcessor.yaml:  |
   application:
     NervIO:
       stream-config:
         client.id: NervIOProcessor-29
         group.id: test-consumer-gr199
         application.id: stateless_processor_id198
       statestore:
         storename: appstore
       jmx.metrics.config:
         collection.interval: 10
       transformer-config:
         customtransform:
           classname: "com.hcl.iAct.Driver"
           config: "{\"storage_type\": \"{{ .Values.storage_type }}\",\"keyvault_enabled\": \"{{ .Values.keyvault_enabled }}\",\"db_url\": \"{{ .Values.db_url }}\",\"db_minidle\": 1,\"db_maxpoolsize\": 2,\"root_drl_path\":\"{{ .Values.root_drl_path }}\",\"miniourl\": \"{{ .Values.miniourl }}\",\"root\": \"snowtopic\",\"bootstrapserver\": \"{{ .Values.kafkaserver }}\",\"topic\": \"scripttopic\",\"keyserializer\": \"{{ .Values.keyserializer }}\",\"valueserializer\": \"{{ .Values.valueserializer }}\",\"alertmanagerurl\":\"{{ .Values.alertmanagerurl }}\",\"kafka.ssl.enable\":\"false\", \"retries\":\"0\"}"
kind:  ConfigMap
metadata:
  name: {{ .Values.appName }}-config
