apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snowmapper.fullname" . }}-snow-iact-mapper
  labels:
  {{- include "snowmapper.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.snowIactMapper.replicas }}
  selector:
    matchLabels:
      name: snow-iact-mapper
    {{- include "snowmapper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPULimit: "1000m"
        sidecar.istio.io/proxyCPU: "200m"
        sidecar.istio.io/proxyMemory: "128Mi"
        sidecar.istio.io/proxyMemoryLimit: "1Gi" 
      labels:
        name: snow-iact-mapper
        app: snow-iact-mapper
        version: 1.0.0
      {{- include "snowmapper.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: iona-demo-sa
      containers:
      - env:
        - name: db_user
          value: "iona_svc"
        - name: db_password
          valueFrom:
            secretKeyRef:
              key: POSTGRES-PASSWORD
              name: {{ .Values.secretName}}
        - name: storagekey
          valueFrom:
            secretKeyRef:
              key: STORAGE-ACCESS-KEY
              name: {{ .Values.secretName}}
        - name: storageaccountname
          valueFrom:
            secretKeyRef:
              key: STORAGE-ACCOUNT-NAME
              name: {{ .Values.secretName}}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.snowIactMapper.snowIactMapper.image.repository }}:{{ .Values.snowIactMapper.snowIactMapper.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: Always
        name: snow-iact-mapper
        resources: {{- toYaml .Values.snowIactMapper.snowIactMapper.resources | nindent
          10 }}
        securityContext:
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/secrets-store
          name: secrets-store-inline
          readOnly: true
        - mountPath: /config/ApplicationCustomProcessor.yaml
          name: snow-iact-mapper-config
          subPath: ApplicationCustomProcessor.yaml
        - mountPath: /config/Global.yaml
          name: global-config
          subPath: Global.yaml
        - mountPath: /tmp
          name: tmp
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      imagePullSecrets:
      - name: acrsecret2
      volumes:
      - csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Values.secretProviderClass }}
        name: secrets-store-inline
      - emptyDir: {}
        name: tmp
      - configMap:
          defaultMode: 420
          name: snow-iact-mapper-config
        name: snow-iact-mapper-config
      - configMap:
          defaultMode: 420
          name: global-config
        name: global-config
