apiVersion: v1
data:
  Global.yaml: |
    global:
     NervIO:
      stream-config:
        schema.registry.url: http://host.docker.internal:8084
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        bootstrap.servers: {{ .Values.snowmapper.kafkaserver }}
      replication.factor: 1
      metrics.recording.level: DEBUG
      statestore:
       storename: globalstore
kind: ConfigMap
metadata:
  name: global-config
