ansibleHl:
  ports:
  - port: 2022
    targetPort: 0
  type: ClusterIP
ansibleProd:
  ansibleProd:
    image:
      repository: "ionatestregistry.azurecr.io/ansible"
      tag: "6.0"
  replicas: 1
kubernetesClusterDomain: cluster.local
pvc:
  pvcAnsibleData:
    storageRequest: 5Gi
  pvcAnsibleSsh:
    storageRequest: 1Gi
