kubernetesClusterDomain: cluster.local
snowIactMapper:
  replicas: 1
  snowIactMapper:
    image:
      repository: "ionatestregistry.azurecr.io/snow-iact-mapper"
      tag: "33.0"
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 100Mi
secretName: "mysecret01"
secretProviderClass: "aws-secrets"
