kubernetesClusterDomain: cluster.local
snowIactMapper:
  replicas: 1
  snowIactMapper:
    image:
      repository: odakscore.azurecr.io/compliant/iona-snowmapper-api
      tag: "3.0"
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 100Mi
secretName: "isee-secret"
secretProviderClass: "ionakv-managed"
